CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE public.actor (
    id_actor integer GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL,
    apellido text NOT NULL,
    pais text NOT NULL,
    biografia text,
    foto text,
    fecha_nacimiento date NOT NULL,
    CONSTRAINT pk_actor PRIMARY KEY (id_actor),
    CONSTRAINT ck_actor_apellido_longitud CHECK (char_length(apellido) >= 2),
    CONSTRAINT ck_actor_nombre_longitud CHECK (char_length(nombre) >= 2)
);

CREATE TABLE public.director (
    id_director integer GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL,
    apellido text NOT NULL,
    pais text NOT NULL,
    biografia text,
    foto text,
    fecha_nacimiento date NOT NULL,
    CONSTRAINT pk_director PRIMARY KEY (id_director),
    CONSTRAINT ck_director_apellido_longitud CHECK (char_length(apellido) >= 2),
    CONSTRAINT ck_director_nombre_longitud CHECK (char_length(nombre) >= 2)
);

CREATE TABLE public.estado_usuario (
    id_estado integer GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL,
    CONSTRAINT pk_estado_usuario PRIMARY KEY (id_estado)
);

CREATE TABLE public.genero (
    id_genero integer GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL,
    descripcion text,
    CONSTRAINT pk_genero PRIMARY KEY (id_genero),
    CONSTRAINT ck_genero_descripcion_longitud CHECK (descripcion IS NULL OR char_length(descripcion) >= 2),
    CONSTRAINT ck_genero_nombre_longitud CHECK (char_length(nombre) >= 2)
);

CREATE TABLE public.plataforma (
    id_plataforma integer GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL,
    pais text NOT NULL,
    biografia text,
    foto text,
    fecha_fundacion date,
    CONSTRAINT pk_plataforma PRIMARY KEY (id_plataforma),
    CONSTRAINT ck_plataforma_nombre_longitud CHECK (char_length(nombre) >= 2)
);

CREATE TABLE public.tipo_obra (
    id_tipo integer GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL,
    descripcion text,
    CONSTRAINT pk_tipo_obra PRIMARY KEY (id_tipo)
);

CREATE TABLE public.usuario (
    id_usuario integer GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL,
    apellido text NOT NULL,
    nombre_usuario text NOT NULL,
    email text NOT NULL,
    contrasena_hash text NOT NULL,
    foto text,
    fecha_nacimiento date NOT NULL,
    rol text NOT NULL DEFAULT 'usuario',
    id_estado integer NOT NULL DEFAULT 1,
    fecha_registro timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    fecha_fin_suspension timestamp with time zone,
    fecha_eliminacion timestamp with time zone,
    CONSTRAINT pk_usuario PRIMARY KEY (id_usuario),
    CONSTRAINT ck_usuario_apellido_longitud CHECK (char_length(apellido) >= 2),
    CONSTRAINT ck_usuario_nombre_longitud CHECK (char_length(nombre) >= 2),
    CONSTRAINT ck_usuario_nombre_usuario_longitud CHECK (char_length(nombre_usuario) >= 2),
    CONSTRAINT ck_usuario_rol CHECK (rol IN ('usuario', 'admin')),
    CONSTRAINT fk_usuario_estado FOREIGN KEY (id_estado) REFERENCES public.estado_usuario (id_estado)
);

CREATE TABLE public.obra (
    id_obra integer GENERATED BY DEFAULT AS IDENTITY,
    id_tipo integer NOT NULL,
    titulo text NOT NULL,
    anio integer NOT NULL,
    sinopsis text NOT NULL,
    duracion integer NOT NULL,
    foto text,
    datos_curiosos text,
    pais_origen text NOT NULL,
    CONSTRAINT pk_obra PRIMARY KEY (id_obra),
    CONSTRAINT ck_obra_anio CHECK (anio >= 1888),
    CONSTRAINT ck_obra_duracion CHECK (duracion > 0),
    CONSTRAINT ck_obra_titulo_longitud CHECK (char_length(titulo) >= 1),
    CONSTRAINT fk_obra_tipo FOREIGN KEY (id_tipo) REFERENCES public.tipo_obra (id_tipo)
);

CREATE TABLE public.articulo (
    id_articulo integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario integer NOT NULL,
    titulo text NOT NULL,
    contenido text NOT NULL,
    fecha timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT pk_articulo PRIMARY KEY (id_articulo),
    CONSTRAINT ck_articulo_contenido_longitud CHECK (char_length(contenido) >= 1),
    CONSTRAINT ck_articulo_titulo_longitud CHECK (char_length(titulo) >= 3),
    CONSTRAINT fk_articulo_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuario (id_usuario)
);

CREATE TABLE public.coleccion (
    id_coleccion integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario integer NOT NULL,
    nombre text NOT NULL,
    CONSTRAINT pk_coleccion PRIMARY KEY (id_coleccion),
    CONSTRAINT ck_coleccion_nombre_longitud CHECK (char_length(nombre) >= 1),
    CONSTRAINT fk_coleccion_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuario (id_usuario)
);

CREATE TABLE public.foro (
    id_foro integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario integer NOT NULL,
    titulo text NOT NULL,
    contenido text NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT pk_foro PRIMARY KEY (id_foro),
    CONSTRAINT ck_foro_contenido_longitud CHECK (char_length(contenido) >= 1),
    CONSTRAINT ck_foro_titulo_longitud CHECK (char_length(titulo) >= 3),
    CONSTRAINT fk_foro_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuario (id_usuario)
);

CREATE TABLE public.obra_actor (
    id_obra integer NOT NULL,
    id_actor integer NOT NULL,
    CONSTRAINT pk_obra_actor PRIMARY KEY (id_obra, id_actor),
    CONSTRAINT fk_obra_actor_actor FOREIGN KEY (id_actor) REFERENCES public.actor (id_actor) ON DELETE CASCADE,
    CONSTRAINT fk_obra_actor_obra FOREIGN KEY (id_obra) REFERENCES public.obra (id_obra) ON DELETE CASCADE
);

CREATE TABLE public.obra_director (
    id_obra integer NOT NULL,
    id_director integer NOT NULL,
    CONSTRAINT pk_obra_director PRIMARY KEY (id_obra, id_director),
    CONSTRAINT fk_obra_director_director FOREIGN KEY (id_director) REFERENCES public.director (id_director) ON DELETE CASCADE,
    CONSTRAINT fk_obra_director_obra FOREIGN KEY (id_obra) REFERENCES public.obra (id_obra) ON DELETE CASCADE
);

CREATE TABLE public.obra_genero (
    id_obra integer NOT NULL,
    id_genero integer NOT NULL,
    CONSTRAINT pk_obra_genero PRIMARY KEY (id_obra, id_genero),
    CONSTRAINT fk_obra_genero_genero FOREIGN KEY (id_genero) REFERENCES public.genero (id_genero),
    CONSTRAINT fk_obra_genero_obra FOREIGN KEY (id_obra) REFERENCES public.obra (id_obra)
);

CREATE TABLE public.obra_plataforma (
    id_obra integer NOT NULL,
    id_plataforma integer NOT NULL,
    CONSTRAINT pk_obra_plataforma PRIMARY KEY (id_obra, id_plataforma),
    CONSTRAINT fk_obra_plataforma_obra FOREIGN KEY (id_obra) REFERENCES public.obra (id_obra),
    CONSTRAINT fk_obra_plataforma_plataforma FOREIGN KEY (id_plataforma) REFERENCES public.plataforma (id_plataforma)
);

CREATE TABLE public.valoracion (
    id_valoracion integer GENERATED BY DEFAULT AS IDENTITY,
    id_obra integer NOT NULL,
    id_usuario integer NOT NULL,
    puntuacion integer NOT NULL,
    resenia text,
    CONSTRAINT pk_valoracion PRIMARY KEY (id_valoracion),
    CONSTRAINT ck_valoracion_puntuacion CHECK (puntuacion BETWEEN 1 AND 10),
    CONSTRAINT fk_valoracion_obra FOREIGN KEY (id_obra) REFERENCES public.obra (id_obra),
    CONSTRAINT fk_valoracion_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuario (id_usuario)
);

CREATE TABLE public.obra_coleccion (
    id_obra integer NOT NULL,
    id_coleccion integer NOT NULL,
    CONSTRAINT pk_obra_coleccion PRIMARY KEY (id_obra, id_coleccion),
    CONSTRAINT fk_obra_coleccion_coleccion FOREIGN KEY (id_coleccion) REFERENCES public.coleccion (id_coleccion) ON DELETE CASCADE,
    CONSTRAINT fk_obra_coleccion_obra FOREIGN KEY (id_obra) REFERENCES public.obra (id_obra) ON DELETE CASCADE
);

CREATE TABLE public.comentario (
    id_comentario integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario integer NOT NULL,
    id_foro integer NOT NULL,
    contenido text NOT NULL,
    fecha_comentario timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT pk_comentario PRIMARY KEY (id_comentario),
    CONSTRAINT ck_comentario_contenido_longitud CHECK (char_length(contenido) >= 1),
    CONSTRAINT fk_comentario_foro FOREIGN KEY (id_foro) REFERENCES public.foro (id_foro),
    CONSTRAINT fk_comentario_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuario (id_usuario)
);

CREATE TABLE public.like_comentario (
    id_usuario integer NOT NULL,
    id_comentario integer NOT NULL,
    CONSTRAINT pk_like_comentario PRIMARY KEY (id_usuario, id_comentario),
    CONSTRAINT fk_like_comentario_comentario FOREIGN KEY (id_comentario) REFERENCES public.comentario (id_comentario),
    CONSTRAINT fk_like_comentario_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuario (id_usuario)
);

INSERT INTO public.estado_usuario (id_estado, nombre)
VALUES (1, 'Activo');
INSERT INTO public.estado_usuario (id_estado, nombre)
VALUES (2, 'Suspendido');
INSERT INTO public.estado_usuario (id_estado, nombre)
VALUES (3, 'Eliminado');

CREATE INDEX "IX_articulo_id_usuario" ON public.articulo (id_usuario);

CREATE UNIQUE INDEX ux_coleccion_usuario_nombre ON public.coleccion (id_usuario, nombre);

CREATE INDEX "IX_comentario_id_foro" ON public.comentario (id_foro);

CREATE INDEX "IX_comentario_id_usuario" ON public.comentario (id_usuario);

CREATE UNIQUE INDEX ux_estado_usuario_nombre ON public.estado_usuario (nombre);

CREATE INDEX "IX_foro_id_usuario" ON public.foro (id_usuario);

CREATE UNIQUE INDEX ux_genero_nombre ON public.genero (nombre);

CREATE INDEX "IX_like_comentario_id_comentario" ON public.like_comentario (id_comentario);

CREATE INDEX "IX_obra_id_tipo" ON public.obra (id_tipo);

CREATE INDEX "IX_obra_actor_id_actor" ON public.obra_actor (id_actor);

CREATE INDEX "IX_obra_coleccion_id_coleccion" ON public.obra_coleccion (id_coleccion);

CREATE INDEX "IX_obra_director_id_director" ON public.obra_director (id_director);

CREATE INDEX "IX_obra_genero_id_genero" ON public.obra_genero (id_genero);

CREATE INDEX "IX_obra_plataforma_id_plataforma" ON public.obra_plataforma (id_plataforma);

CREATE UNIQUE INDEX ux_plataforma_nombre ON public.plataforma (nombre);

CREATE UNIQUE INDEX ux_tipo_obra_nombre ON public.tipo_obra (nombre);

CREATE INDEX "IX_usuario_id_estado" ON public.usuario (id_estado);

CREATE UNIQUE INDEX ux_usuario_email ON public.usuario (email);

CREATE UNIQUE INDEX ux_usuario_nombre_usuario ON public.usuario (nombre_usuario);

CREATE INDEX "IX_valoracion_id_obra" ON public.valoracion (id_obra);

CREATE UNIQUE INDEX ux_valoracion_usuario_obra ON public.valoracion (id_usuario, id_obra);

SELECT setval(
    pg_get_serial_sequence('public.estado_usuario', 'id_estado'),
    GREATEST(
        (SELECT MAX(id_estado) FROM public.estado_usuario) + 1,
        nextval(pg_get_serial_sequence('public.estado_usuario', 'id_estado'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260727171628_InitialCreate', '10.0.10');

COMMIT;

