// <auto-generated />
using System;
using DigitalParalysis.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DigitalParalysis.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DigitalParalysisDbContext))]
    partial class DigitalParalysisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_actor");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellido");

                    b.Property<string>("Biografia")
                        .HasColumnType("text")
                        .HasColumnName("biografia");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Foto")
                        .HasColumnType("text")
                        .HasColumnName("foto");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pais");

                    b.HasKey("Id")
                        .HasName("pk_actor");

                    b.ToTable("actor", "public", t =>
                        {
                            t.HasCheckConstraint("ck_actor_apellido_longitud", "char_length(apellido) >= 2");

                            t.HasCheckConstraint("ck_actor_nombre_longitud", "char_length(nombre) >= 2");
                        });
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_articulo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contenido");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("pk_articulo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("articulo", "public", t =>
                        {
                            t.HasCheckConstraint("ck_articulo_contenido_longitud", "char_length(contenido) >= 1");

                            t.HasCheckConstraint("ck_articulo_titulo_longitud", "char_length(titulo) >= 3");
                        });
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.Coleccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_coleccion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_coleccion");

                    b.HasIndex("IdUsuario", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_coleccion_usuario_nombre");

                    b.ToTable("coleccion", "public", t =>
                        {
                            t.HasCheckConstraint("ck_coleccion_nombre_longitud", "char_length(nombre) >= 1");
                        });
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_comentario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contenido");

                    b.Property<DateTime>("FechaComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_comentario")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdForo")
                        .HasColumnType("integer")
                        .HasColumnName("id_foro");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id")
                        .HasName("pk_comentario");

                    b.HasIndex("IdForo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("comentario", "public", t =>
                        {
                            t.HasCheckConstraint("ck_comentario_contenido_longitud", "char_length(contenido) >= 1");
                        });
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_director");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellido");

                    b.Property<string>("Biografia")
                        .HasColumnType("text")
                        .HasColumnName("biografia");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Foto")
                        .HasColumnType("text")
                        .HasColumnName("foto");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pais");

                    b.HasKey("Id")
                        .HasName("pk_director");

                    b.ToTable("director", "public", t =>
                        {
                            t.HasCheckConstraint("ck_director_apellido_longitud", "char_length(apellido) >= 2");

                            t.HasCheckConstraint("ck_director_nombre_longitud", "char_length(nombre) >= 2");
                        });
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.EstadoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_estado");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_estado_usuario");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_estado_usuario_nombre");

                    b.ToTable("estado_usuario", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Activo"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Suspendido"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Eliminado"
                        });
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.Foro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_foro");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contenido");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("pk_foro");

                    b.HasIndex("IdUsuario");

                    b.ToTable("foro", "public", t =>
                        {
                            t.HasCheckConstraint("ck_foro_contenido_longitud", "char_length(contenido) >= 1");

                            t.HasCheckConstraint("ck_foro_titulo_longitud", "char_length(titulo) >= 3");
                        });
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_genero");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_genero");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_genero_nombre");

                    b.ToTable("genero", "public", t =>
                        {
                            t.HasCheckConstraint("ck_genero_descripcion_longitud", "descripcion IS NULL OR char_length(descripcion) >= 2");

                            t.HasCheckConstraint("ck_genero_nombre_longitud", "char_length(nombre) >= 2");
                        });
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.Like", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<int>("IdComentario")
                        .HasColumnType("integer")
                        .HasColumnName("id_comentario");

                    b.HasKey("IdUsuario", "IdComentario")
                        .HasName("pk_like_comentario");

                    b.HasIndex("IdComentario");

                    b.ToTable("like_comentario", "public");
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.Obra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_obra");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer")
                        .HasColumnName("anio");

                    b.Property<string>("DatosCuriosos")
                        .HasColumnType("text")
                        .HasColumnName("datos_curiosos");

                    b.Property<int>("Duracion")
                        .HasColumnType("integer")
                        .HasColumnName("duracion");

                    b.Property<string>("Foto")
                        .HasColumnType("text")
                        .HasColumnName("foto");

                    b.Property<int>("IdTipoObra")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo");

                    b.Property<string>("PaisOrigen")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pais_origen");

                    b.Property<string>("Sinopsis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sinopsis");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("pk_obra");

                    b.HasIndex("IdTipoObra");

                    b.ToTable("obra", "public", t =>
                        {
                            t.HasCheckConstraint("ck_obra_anio", "anio >= 1888");

                            t.HasCheckConstraint("ck_obra_duracion", "duracion > 0");

                            t.HasCheckConstraint("ck_obra_titulo_longitud", "char_length(titulo) >= 1");
                        });
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.ObraActor", b =>
                {
                    b.Property<int>("IdObra")
                        .HasColumnType("integer")
                        .HasColumnName("id_obra");

                    b.Property<int>("IdActor")
                        .HasColumnType("integer")
                        .HasColumnName("id_actor");

                    b.HasKey("IdObra", "IdActor")
                        .HasName("pk_obra_actor");

                    b.HasIndex("IdActor");

                    b.ToTable("obra_actor", "public");
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.ObraColeccion", b =>
                {
                    b.Property<int>("IdObra")
                        .HasColumnType("integer")
                        .HasColumnName("id_obra");

                    b.Property<int>("IdColeccion")
                        .HasColumnType("integer")
                        .HasColumnName("id_coleccion");

                    b.HasKey("IdObra", "IdColeccion")
                        .HasName("pk_obra_coleccion");

                    b.HasIndex("IdColeccion");

                    b.ToTable("obra_coleccion", "public");
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.ObraDirector", b =>
                {
                    b.Property<int>("IdObra")
                        .HasColumnType("integer")
                        .HasColumnName("id_obra");

                    b.Property<int>("IdDirector")
                        .HasColumnType("integer")
                        .HasColumnName("id_director");

                    b.HasKey("IdObra", "IdDirector")
                        .HasName("pk_obra_director");

                    b.HasIndex("IdDirector");

                    b.ToTable("obra_director", "public");
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.ObraGenero", b =>
                {
                    b.Property<int>("IdObra")
                        .HasColumnType("integer")
                        .HasColumnName("id_obra");

                    b.Property<int>("IdGenero")
                        .HasColumnType("integer")
                        .HasColumnName("id_genero");

                    b.HasKey("IdObra", "IdGenero")
                        .HasName("pk_obra_genero");

                    b.HasIndex("IdGenero");

                    b.ToTable("obra_genero", "public");
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.ObraPlataforma", b =>
                {
                    b.Property<int>("IdObra")
                        .HasColumnType("integer")
                        .HasColumnName("id_obra");

                    b.Property<int>("IdPlataforma")
                        .HasColumnType("integer")
                        .HasColumnName("id_plataforma");

                    b.HasKey("IdObra", "IdPlataforma")
                        .HasName("pk_obra_plataforma");

                    b.HasIndex("IdPlataforma");

                    b.ToTable("obra_plataforma", "public");
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.Plataforma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_plataforma");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Biografia")
                        .HasColumnType("text")
                        .HasColumnName("biografia");

                    b.Property<DateOnly?>("FechaFundacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fundacion");

                    b.Property<string>("Foto")
                        .HasColumnType("text")
                        .HasColumnName("foto");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pais");

                    b.HasKey("Id")
                        .HasName("pk_plataforma");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_plataforma_nombre");

                    b.ToTable("plataforma", "public", t =>
                        {
                            t.HasCheckConstraint("ck_plataforma_nombre_longitud", "char_length(nombre) >= 2");
                        });
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.TipoObra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_tipo_obra");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_tipo_obra_nombre");

                    b.ToTable("tipo_obra", "public");
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellido");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contrasena_hash");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_eliminacion");

                    b.Property<DateTime?>("FechaFinSuspension")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin_suspension");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Foto")
                        .HasColumnType("text")
                        .HasColumnName("foto");

                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("id_estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasDefaultValue("usuario")
                        .HasColumnName("rol");

                    b.HasKey("Id")
                        .HasName("pk_usuario");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_usuario_email");

                    b.HasIndex("IdEstado");

                    b.HasIndex("NombreUsuario")
                        .IsUnique()
                        .HasDatabaseName("ux_usuario_nombre_usuario");

                    b.ToTable("usuario", "public", t =>
                        {
                            t.HasCheckConstraint("ck_usuario_apellido_longitud", "char_length(apellido) >= 2");

                            t.HasCheckConstraint("ck_usuario_nombre_longitud", "char_length(nombre) >= 2");

                            t.HasCheckConstraint("ck_usuario_nombre_usuario_longitud", "char_length(nombre_usuario) >= 2");

                            t.HasCheckConstraint("ck_usuario_rol", "rol IN ('usuario', 'admin')");
                        });
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.Valoracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_valoracion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdObra")
                        .HasColumnType("integer")
                        .HasColumnName("id_obra");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<int>("Puntuacion")
                        .HasColumnType("integer")
                        .HasColumnName("puntuacion");

                    b.Property<string>("Resenia")
                        .HasColumnType("text")
                        .HasColumnName("resenia");

                    b.HasKey("Id")
                        .HasName("pk_valoracion");

                    b.HasIndex("IdObra");

                    b.HasIndex("IdUsuario", "IdObra")
                        .IsUnique()
                        .HasDatabaseName("ux_valoracion_usuario_obra");

                    b.ToTable("valoracion", "public", t =>
                        {
                            t.HasCheckConstraint("ck_valoracion_puntuacion", "puntuacion BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.Articulo", b =>
                {
                    b.HasOne("DigitalParalysis.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Articulos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_articulo_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.Coleccion", b =>
                {
                    b.HasOne("DigitalParalysis.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Colecciones")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_coleccion_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.Comentario", b =>
                {
                    b.HasOne("DigitalParalysis.Domain.Entities.Foro", "Foro")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdForo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_comentario_foro");

                    b.HasOne("DigitalParalysis.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_comentario_usuario");

                    b.Navigation("Foro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.Foro", b =>
                {
                    b.HasOne("DigitalParalysis.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Foros")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_foro_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.Like", b =>
                {
                    b.HasOne("DigitalParalysis.Domain.Entities.Comentario", "Comentario")
                        .WithMany("Likes")
                        .HasForeignKey("IdComentario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_like_comentario_comentario");

                    b.HasOne("DigitalParalysis.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Likes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_like_comentario_usuario");

                    b.Navigation("Comentario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.Obra", b =>
                {
                    b.HasOne("DigitalParalysis.Domain.Entities.TipoObra", "TipoObra")
                        .WithMany("Obras")
                        .HasForeignKey("IdTipoObra")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_obra_tipo");

                    b.Navigation("TipoObra");
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.ObraActor", b =>
                {
                    b.HasOne("DigitalParalysis.Domain.Entities.Actor", "Actor")
                        .WithMany("ObraActores")
                        .HasForeignKey("IdActor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_obra_actor_actor");

                    b.HasOne("DigitalParalysis.Domain.Entities.Obra", "Obra")
                        .WithMany("ObraActores")
                        .HasForeignKey("IdObra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_obra_actor_obra");

                    b.Navigation("Actor");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.ObraColeccion", b =>
                {
                    b.HasOne("DigitalParalysis.Domain.Entities.Coleccion", "Coleccion")
                        .WithMany("ObraColecciones")
                        .HasForeignKey("IdColeccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_obra_coleccion_coleccion");

                    b.HasOne("DigitalParalysis.Domain.Entities.Obra", "Obra")
                        .WithMany("ObraColecciones")
                        .HasForeignKey("IdObra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_obra_coleccion_obra");

                    b.Navigation("Coleccion");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.ObraDirector", b =>
                {
                    b.HasOne("DigitalParalysis.Domain.Entities.Director", "Director")
                        .WithMany("ObraDirectores")
                        .HasForeignKey("IdDirector")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_obra_director_director");

                    b.HasOne("DigitalParalysis.Domain.Entities.Obra", "Obra")
                        .WithMany("ObraDirectores")
                        .HasForeignKey("IdObra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_obra_director_obra");

                    b.Navigation("Director");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.ObraGenero", b =>
                {
                    b.HasOne("DigitalParalysis.Domain.Entities.Genero", "Genero")
                        .WithMany("ObraGeneros")
                        .HasForeignKey("IdGenero")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_obra_genero_genero");

                    b.HasOne("DigitalParalysis.Domain.Entities.Obra", "Obra")
                        .WithMany("ObraGeneros")
                        .HasForeignKey("IdObra")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_obra_genero_obra");

                    b.Navigation("Genero");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.ObraPlataforma", b =>
                {
                    b.HasOne("DigitalParalysis.Domain.Entities.Obra", "Obra")
                        .WithMany("ObraPlataformas")
                        .HasForeignKey("IdObra")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_obra_plataforma_obra");

                    b.HasOne("DigitalParalysis.Domain.Entities.Plataforma", "Plataforma")
                        .WithMany("ObraPlataformas")
                        .HasForeignKey("IdPlataforma")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_obra_plataforma_plataforma");

                    b.Navigation("Obra");

                    b.Navigation("Plataforma");
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("DigitalParalysis.Domain.Entities.EstadoUsuario", "EstadoUsuario")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_estado");

                    b.Navigation("EstadoUsuario");
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.Valoracion", b =>
                {
                    b.HasOne("DigitalParalysis.Domain.Entities.Obra", "Obra")
                        .WithMany("Valoraciones")
                        .HasForeignKey("IdObra")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_valoracion_obra");

                    b.HasOne("DigitalParalysis.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Valoraciones")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_valoracion_usuario");

                    b.Navigation("Obra");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.Actor", b =>
                {
                    b.Navigation("ObraActores");
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.Coleccion", b =>
                {
                    b.Navigation("ObraColecciones");
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.Comentario", b =>
                {
                    b.Navigation("Likes");
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.Director", b =>
                {
                    b.Navigation("ObraDirectores");
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.EstadoUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.Foro", b =>
                {
                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.Genero", b =>
                {
                    b.Navigation("ObraGeneros");
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.Obra", b =>
                {
                    b.Navigation("ObraActores");

                    b.Navigation("ObraColecciones");

                    b.Navigation("ObraDirectores");

                    b.Navigation("ObraGeneros");

                    b.Navigation("ObraPlataformas");

                    b.Navigation("Valoraciones");
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.Plataforma", b =>
                {
                    b.Navigation("ObraPlataformas");
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.TipoObra", b =>
                {
                    b.Navigation("Obras");
                });

            modelBuilder.Entity("DigitalParalysis.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Articulos");

                    b.Navigation("Colecciones");

                    b.Navigation("Comentarios");

                    b.Navigation("Foros");

                    b.Navigation("Likes");

                    b.Navigation("Valoraciones");
                });
#pragma warning restore 612, 618
        }
    }
}
